version: '3.9'
services:
  webssh:
    build: ./ubuntu1/.
    networks:
      challenge:
        ipv4_address: 172.16.88.2
    ports:
     - "8080:80"
     - "2222:22"   
networks:
  challenge:
    ipam:
      driver: default
      config:
        - subnet: 172.16.88.0/24
